### ISSUE TITLE
卡哥仓库主页的网址链接不对

### ISSUE THREAD

**Issue by huawuque404** [youngyangyang04/kamacoder-solutions#5]
![image](https://github.com/youngyangyang04/kamacoder-solutions/assets/109327586/ef0d22bd-bc72-410e-a540-a44609a90c9e)

**Comment by youngyangyang04** [comment]
> ![image](https://user-images.githubusercontent.com/109327586/256737026-ef0d22bd-bc72-410e-a540-a44609a90c9e.png)

已修复
