### ISSUE TITLE
第40题 python当算法相同时会出现内存不足的情况

### ISSUE THREAD

**Issue by Challis-yin** [youngyangyang04/kamacoder-solutions#89]
代码如下
`def get_count(n):
    nums = [0 for _ in range(n+1)]
    nums[1] = 1
    for i in range(2, n+1):
        if i%2 == 0:
            nums[i] = nums[i//2]+1
        else:
            nums[i] = min(nums[i-1]+1, nums[(i+1)//2]+2)
    return nums[-1]

n = abs(int(input()))
print(get_count(n=n)) `
与C++解法和Java解法算法相同，但是报错超时

**Comment by Challis-yin** [comment]
@youngyangyang04

**Comment by YakultGo** [comment]
我提交了一个更加正确的解法，使用动态规划的解法并不能解决当x很大的时候，可以看我的提的PR

**Comment by charon2121** [comment]
算法正确，但是 Python 在消耗内存空间这块确实出人意料。。。
已经修改了后台的数据范围，确保在相同的思路情况下，Python 也能通过测试数据。

**Comment by youngyangyang04** [comment]
> 

👍🏻
